name: sandfriends_web
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+3

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6+3
  image_cropper: ^3.0.1
  image: ^4.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  calendar_date_picker2: ^0.3.6
  loading_animation_widget: ^1.2.0+4
  http: ^0.13.5
  extended_masked_text: ^2.3.1
  syncfusion_flutter_datagrid: ^20.4.50
  fl_chart: ^0.60.0
  intl: ^0.18.1
  scrollable_positioned_list: ^0.3.5
  auto_size_text: ^3.0.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.1.0
  localstorage: ^4.0.1+2
  cached_network_image: ^3.2.3
  url_launcher: ^6.2.1
  flutter_secure_storage: ^9.0.0
  palette_generator: ^0.3.3+3
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.7.2
  flutter_local_notifications: ^16.1.0
  tuple: ^2.0.2
  two_dimensional_scrollables: ^0.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/full_logo_negative.svg
    - assets/icon/full_logo_positive.svg
    - assets/icon/logo_negative.svg
    - assets/icon/logo_positive.svg
    - assets/icon/home.svg
    - assets/icon/calendar.svg
    - assets/icon/star.svg
    - assets/icon/analytics.svg
    - assets/icon/help.svg
    - assets/icon/finance.svg
    - assets/icon/court.svg
    - assets/icon/config.svg
    - assets/icon/eye_closed.svg
    - assets/icon/eye_open.svg
    - assets/icon/lock.svg
    - assets/icon/email.svg
    - assets/icon/arrow_left.svg
    - assets/icon/happy_face.svg
    - assets/icon/sad_face.svg
    - assets/icon/plus.svg
    - assets/icon/three_dots.svg
    - assets/icon/double_arrow_left.svg
    - assets/icon/double_arrow_right.svg
    - assets/icon/x.svg
    - assets/icon/user.svg
    - assets/icon/user_plus.svg
    - assets/icon/user_group.svg
    - assets/icon/logout.svg
    - assets/icon/whatsapp.svg
    - assets/icon/clock.svg
    - assets/icon/chevron_up.svg
    - assets/icon/chevron_down.svg
    - assets/icon/chevron_left.svg
    - assets/icon/chevron_right.svg
    - assets/icon/edit.svg
    - assets/icon/file.svg
    - assets/icon/forecast.svg
    - assets/icon/money.svg
    - assets/icon/check.svg
    - assets/icon/attention.svg
    - assets/icon/block.svg
    - assets/icon/check_circle.svg
    - assets/icon/phone_hand.svg
    - assets/icon/delete.svg
    - assets/icon/delete_filter.svg
    - assets/icon/menu_burger.svg
    - assets/icon/notification_on.svg
    - assets/icon/notification_off.svg
    - assets/icon/already_paid.svg
    - assets/icon/needs_payment.svg
    - assets/icon/settings.svg
    - assets/icon/calendar_add.svg
    - assets/icon/info.svg
    - assets/icon/search.svg
    - assets/icon/sport_1.svg
    - assets/icon/sport_2.svg
    - assets/icon/sport_3.svg

    - assets/people/calendar.svg
    - assets/people/clock.svg
    - assets/people/onboarding.svg
    - assets/people/email_confirmation_store.svg
    - assets/people/email_confirmation_user.svg


    - assets/app_icon/prod.png
    - assets/app_icon/demo.png
    - assets/app_icon/dev.png

    - assets/full_logo_negative_160.png
    - assets/full_logo_negative_284.png
    - assets/full_logo_positive_160.png
    - assets/full_logo_positive_284.png
    - assets/full_logo_positive_284_courts.png
    - assets/full_logo_negative_284_courts.png
    - assets/logo_64.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
