// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqB0l8u_ToZjzmXnlRD_bm7xyvGG6yhxw',
    appId: '1:329100803665:web:b0e6d8558c2dc6c3af4270',
    messagingSenderId: '329100803665',
    projectId: 'sandfriends-prod',
    authDomain: 'sandfriends-prod.firebaseapp.com',
    storageBucket: 'sandfriends-prod.appspot.com',
    measurementId: 'G-ELPPBT8PFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACNkmqOyYaCZKYyDuZRDpYp1weZrI3aqI',
    appId: '1:329100803665:android:8ead35e5e7c0d150af4270',
    messagingSenderId: '329100803665',
    projectId: 'sandfriends-prod',
    storageBucket: 'sandfriends-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT0kQqFx2InNi3bVKsmN0NhkbqyXhFK-Q',
    appId: '1:329100803665:ios:da38d869a1e40dd9af4270',
    messagingSenderId: '329100803665',
    projectId: 'sandfriends-prod',
    storageBucket: 'sandfriends-prod.appspot.com',
    iosClientId:
        '329100803665-n566cd89i1hki8agb7qit1at2odbhgmg.apps.googleusercontent.com',
    iosBundleId: 'com.sandfriends.app.prod',
  );
}
